name = "polpo-hotesse-worker"
main = "src/index.js"
compatibility_date = "2025-01-01"

account_id = "a765efd32045142f11db525bac5c136e"

[[d1_databases]]
binding = "DB"
database_name = "polpo-hotesse-db"
database_id = "f0393625-4e82-4ea7-9bc3-94f5af444a65"

[ai]
binding = "AI"

[vars]
ZENCHEF_IMPORT_MODEL = "@cf/llava-hf/llava-1.5-7b-hf"